

services:
  postgres:
    image: postgres:15
    container_name: rwanda_ride_db
    environment:
      POSTGRES_DB: bestprogramming
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: rwanda_ride_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bestprogramming
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: shema
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8081:8081"

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rwanda_ride_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
