services:
  postgres:
    image: postgres:15
    container_name: rwanda_ride_db
    environment:
      POSTGRES_DB: rwanda_ride
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: shema
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: rwanda_ride_backend
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/rwanda_ride
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=shema
      # Email configuration
      - SPRING_MAIL_HOST=smtp.gmail.com
      - SPRING_MAIL_PORT=587
      - SPRING_MAIL_USERNAME=your-email@gmail.com
      - SPRING_MAIL_PASSWORD=your-app-password
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH=true
      - SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE=true
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rwanda_ride_frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  postgres_data:
